import pandas as pd

df = pd.read_excel("app/aux_data/base_pesos.xlsx")

# Separar os valores e coletar todos os subjects únicos
unique_subjects = set()

# Iterar sobre cada linha da coluna subjects
for subjects in df["Gêneros"]:
    # Dividir por vírgula e remover espaços em branco
    subjects_list = [subject.strip().lower() for subject in subjects.split(",")]
    # Adicionar os subjects ao conjunto
    unique_subjects.update(subjects_list)

# Convertendo para uma lista ordenada para fácil visualização
unique_subjects = sorted(unique_subjects)
print("Subjects únicos:")
print(unique_subjects)


subject_to_genre = {
    "-": "Gênero não definido",
    "18.05 english literature": "Literatura",
    "19th century": "Histórico",
    "20th century": "Histórico",
    "823/.8": "Literatura",
    "accessible book": "Gênero não definido",
    "action & adventure": "Aventura",
    "adaptations": "Ficção Adaptada",
    "adult": "Literatura para Adultos",
    "adultery": "Drama",
    "adventure and adventurers": "Aventura",
    "african american women": "Literatura Diversa",
    "american": "Literatura Americana",
    "american fiction": "Ficção Americana",
    "american fiction (fictional works by one author)": "Ficção Americana",
    "american literature": "Literatura Americana",
    "american poetry": "Poesia",
    "amerikanisches englisch": "Literatura",
    "amitié": "Amizade",
    "amour": "Romance",
    "amours": "Romance",
    "animals": "Ficção Animal",
    "aristocracy (social class)": "Drama Social",
    "asesinato": "Ficção de Crime",
    "authors": "Gênero não definido",
    "autobiographical fiction": "Biografia",
    "bildungsromans": "Ficção de Formação",
    "biographical": "Biografia",
    "biographies": "Biografia",
    "biography": "Biografia",
    "biography & autobiography / personal memoirs": "Biografia",
    "books": "Gênero não definido",
    "books and reading": "Gênero não definido",
    "british": "Literatura Britânica",
    "british and irish drama (dramatic works by one author)": "Drama",
    "british and irish fiction (fictional works by one author)": "Ficção Britânica",
    "canadian fiction (fictional works by one author)": "Ficção Canadense",
    "cartoons and comics": "Quadrinhos",
    "chang pian xiao shuo": "Ficção Chinesa",
    "child and youth fiction": "Ficção Juvenil",
    "children": "Literatura Infantil",
    "children's books": "Literatura Infantil",
    "children's fiction": "Ficção Infantil",
    "children's plays": "Teatro Infantil",
    "children's stories": "Contos Infantis",
    "chinese language": "Literatura Chinesa",
    "classic": "Ficção Clássica",
    "classic fiction": "Ficção Clássica",
    "classic literature": "Ficção Clássica",
    "classical literature": "Ficção Clássica",
    "classics": "Ficção Clássica",
    "collectionid:eaneschallenge": "Gênero não definido",
    "collections": "Antologias",
    "college students": "Literatura Juvenil",
    "coloring books": "Livros para Colorir",
    "comic books": "Quadrinhos",
    "comics & graphic novels": "Quadrinhos",
    "coming of age": "Ficção de Formação",
    "coming-of-age": "Ficção de Formação",
    "concours et compétitions": "Gênero não definido",
    "conduct of life": "Autoajuda",
    "contemporary": "Ficção Contemporânea",
    "contemporary women": "Literatura Feminina",
    "contests": "Gênero não definido",
    "continental european fiction (fictional works by one author)": "Ficção Europeia",
    "count (fictitious character)": "Ficção",
    "courts and courtiers": "Histórico",
    "courtship": "Romance",
    "crime": "Ficção de Crime",
    "crimes against": "Ficção de Crime",
    "criminals": "Ficção de Crime",
    "criticism and interpretation": "Crítica Literária",
    "cuentos de amor": "Romance",
    "customs": "Antropologia",
    "death": "Drama",
    "detective and mystery stories": "Mistério",
    "dictionaries": "Referência",
    "domestic fiction": "Drama Familiar",
    "dracula": "Ficção de Horror",
    "drama": "Drama",
    "drama (dramatic works by one author)": "Drama",
    "dreams": "Ficção Fantástica",
    "dystopian": "Ficção Dystópica",
    "dystopian fiction": "Ficção Dystópica",
    "dystopias": "Ficção Dystópica",
    "england": "Literatura Britânica",
    "england in fiction": "Ficção Britânica",
    "english": "Literatura",
    "english adventure stories": "Aventura",
    "english fantasy fiction": "Ficção Fantástica",
    "english fantasy literature": "Ficção Fantástica",
    "english fiction": "Ficção",
    "english horror tales": "Ficção de Horror",
    "english language": "Referência",
    "english literature": "Literatura",
    "erotica": "Erótica",
    "escuelas": "Gênero não definido",
    "escuelas secundarias": "Gênero não definido",
    "etc.": "Gênero não definido",
    "etc. pour la jeunesse": "Literatura Juvenil",
    "examinations": "Gênero não definido",
    "facsimiles": "Gênero não definido",
    "fairy tales": "Contos de Fadas",
    "families": "Drama Familiar",
    "familles": "Drama Familiar",
    "family": "Drama Familiar",
    "family life": "Drama Familiar",
    "fantasy": "Ficção Fantástica",
    "fantasy & magic": "Ficção Fantástica",
    "fantasy fiction": "Ficção Fantástica",
    "fantasy in fiction": "Ficção Fantástica",
    "fantasía": "Ficção Fantástica",
    "feminism": "Literatura Feminina",
    "ficción": "Ficção",
    "ficción juvenil": "Ficção Juvenil",
    "fiction": "Ficção",
    "fiction / coming of age": "Ficção de Formação",
    "fiction / literary": "Ficção Literária",
    "fiction / psychological": "Ficção Psicológica",
    "fiction classics": "Ficção Clássica",
    "fiction in english": "Ficção Americana",
    "fictional works": "Ficção",
    "first loves": "Romance",
    "folklore": "Folclore",
    "foreign relations": "Política",
    "friends": "Amizade",
    "friendship": "Amizade",
    "general": "Gênero não definido",
    "german": "Literatura Alemã",
    "ghost": "Ficção de Horror",
    "girls": "Literatura Feminina",
    "good and evil": "Filosofia",
    "gothic": "Ficção Gótica",
    "gothic fiction": "Ficção Gótica",
    "graphic novels": "Quadrinhos",
    "great britain": "Literatura Britânica",
    "hermanas": "Relações Familiares",
    "high interest-low vocabulary books": "Literatura Juvenil",
    "high school students": "Ficção Juvenil",
    "histoire": "História",
    "historia": "História",
    "historical": "Ficção Histórica",
    "historical fiction": "Ficção Histórica",
    "history": "História",
    "history and criticism": "História",
    "hombres": "Literatura Masculina",
    "horror": "Ficção de Horror",
    "horror & ghost stories": "Ficção de Horror",
    "horror fiction": "Ficção de Horror",
    "horror stories": "Ficção de Horror",
    "horror tales": "Ficção de Horror",
    "humorous stories": "Comédia",
    "illustrations": "Arte",
    "interpersonal relations": "Psicologia",
    "investigation": "Mistério",
    "jeunes femmes": "Literatura Feminina",
    "juvenile": "Ficção Juvenil",
    "juvenile fiction": "Ficção Juvenil",
    "juvenile literature": "Ficção Juvenil",
    "juvenile works": "Ficção Juvenil",
    "jóvenes (mujeres)": "Literatura Feminina",
    "king": "Literatura de Fantasia",
    "large type books": "Gênero não definido",
    "lectures et morceaux choisis": "Literatura",
    "legends": "Folclore",
    "lgbtq novels": "Literatura LGBTQ+",
    "literary": "Literatura",
    "literary criticism": "Crítica Literária",
    "literary fiction": "Ficção Literária",
    "literatura inglesa": "Literatura Inglesa",
    "literature": "Literatura",
    "literature and fiction": "Literatura",
    "literature and fiction (general)": "Literatura",
    "london (england)": "Literatura Britânica",
    "long now manual for civilization": "Gênero não definido",
    "love": "Romance",
    "love & romance": "Romance",
    "love stories": "Romance",
    "madres e hijas": "Drama Familiar",
    "magic": "Ficção de Fantasia",
    "magic in fiction": "Ficção de Fantasia",
    "man-woman relationship": "Romance",
    "man-woman relationships": "Romance",
    "manners": "Gênero não definido",
    "manners and customs": "Antropologia",
    "manuscripts": "História",
    "married people": "Drama",
    "married women": "Drama Feminino",
    "materiales en español": "Gênero não definido",
    "men": "Literatura Masculina",
    "monsters": "Ficção de Horror",
    "morale pratique": "Filosofia",
    "mort": "Drama",
    "mothers": "Drama Familiar",
    "mothers and daughters": "Drama Familiar",
    "motion pictures": "Cinema",
    "mujeres casadas": "Drama Feminino",
    "murder": "Ficção de Crime",
    "murderers": "Ficção de Crime",
    "mystery": "Mistério",
    "mystery & detective": "Mistério",
    "mœurs et coutumes": "Antropologia",
    "new york (n.y.)": "Literatura Americana",
    "new york times bestseller": "Gênero não definido",
    "new york times reviewed": "Gênero não definido",
    "nobility": "Histórico",
    "nouvelles": "Contos",
    "novel": "Romance",
    "novela": "Romance",
    "novela estadounidense": "Ficção Americana",
    "novela fantástica": "Ficção de Fantasia",
    "novela inglesa": "Ficção Britânica",
    "novela juvenil": "Ficção Juvenil",
    "novels": "Romance",
    "open library staff picks": "Gênero não definido",
    "open_syllabus_project": "Gênero não definido",
    "orphans": "Drama",
    "paranormal": "Ficção de Horror",
    "paranormal fiction": "Ficção de Horror",
    "physicians": "Ficção Médica",
    "poetry": "Poesia",
    "polish language materials": "Gênero não definido",
    "political": "Política",
    "premier amour": "Romance",
    "private investigators": "Mistério",
    "protected daisy": "Gênero não definido",
    "psychological": "Ficção Psicológica",
    "psychological fiction": "Ficção Psicológica",
    "psychology": "Psicologia",
    "readers": "Literatura Juvenil",
    "readers for new literates": "Literatura Juvenil",
    "reading level-grade 10": "Literatura Juvenil",
    "reading level-grade 11": "Literatura Juvenil",
    "reading level-grade 12": "Literatura Juvenil",
    "reading level-grade 7": "Literatura Juvenil",
    "reading level-grade 8": "Literatura Juvenil",
    "reading level-grade 9": "Literatura Juvenil",
    "reading materials": "Literatura Juvenil",
    "relaciones hombre-mujer": "Relações",
    "relaciones humanas": "Relações",
    "revenge": "Drama",
    "rhetoric": "Literatura",
    "rich people": "Drama Social",
    "roman": "Romance",
    "roman policier": "Ficção Policial",
    "roman pour jeunes adultes": "Ficção Juvenil",
    "roman pour la jeunesse": "Literatura Infantil",
    "romance": "Romance",
    "romance fiction": "Romance",
    "romans": "Romance",
    "russian fiction": "Ficção Russa",
    "russian language materials": "Gênero não definido",
    "school stories": "Ficção Juvenil",
    "schools": "Gênero não definido",
    "science fiction": "Ficção Científica",
    "science fiction & fantasy": "Ficção Científica e Fantástica",
    "self-realization": "Autoajuda",
    "sexual behavior": "Psicologia",
    "short stories": "Contos",
    "short stories (single author)": "Contos",
    "sisters": "Drama Familiar",
    "social classes": "Drama Social",
    "social conditions": "Drama Social",
    "social life": "Aspectos Sociais",
    "social life and customs": "Antropologia",
    "social themes": "Aspectos Sociais",
    "solitude": "Drama",
    "sources": "Gênero não definido",
    "spanish": "Literatura Hispânica",
    "spanish language": "Literatura Hispânica",
    "spanish language materials": "Gênero não definido",
    "specimens": "Gênero não definido",
    "stories": "Ficção",
    "strips": "Quadrinhos",
    "study and teaching": "Educação",
    "study guides": "Educação",
    "suicide": "Drama",
    "supernatural": "Ficção Fantástica",
    "survival": "Aventura",
    "suspense": "Mistério",
    "suspense fiction": "Mistério",
    "sœurs": "Drama Familiar",
    "teen fiction": "Ficção Juvenil",
    "teenage girls": "Ficção Juvenil",
    "teenagers": "Ficção Juvenil",
    "textbooks for foreign speakers": "Educação",
    "textual criticism": "Crítica Literária",
    "thriller": "Mistério",
    "thrillers": "Mistério",
    "totalitarianism": "Ficção Política",
    "toy and movable books": "Literatura Infantil",
    "traducciones al español": "Gênero não definido",
    "translations from english": "Gênero não definido",
    "translations into chinese": "Gênero não definido",
    "translations into english": "Gênero não definido",
    "translations into russian": "Gênero não definido",
    "translations into spanish": "Gênero não definido",
    "travel": "Viagem",
    "triangles (interpersonal relations)": "Relações",
    "united states": "Literatura Americana",
    "upper class": "Drama Social",
    "vampires": "Ficção de Horror",
    "vampiros": "Ficção de Horror",
    "wealth": "Drama Social",
    "witchcraft": "Ficção de Fantasia",
    "witches": "Ficção de Fantasia",
    "wives": "Drama",
    "wizards": "Ficção de Fantasia",
    "women": "Literatura Feminina",
    "women authors": "Literatura Feminina",
    "ya": "Ficção Juvenil",
    "ying yu": "Literatura Chinesa",
    "young adult": "Ficção Juvenil",
    "young adult fiction": "Ficção Juvenil",
    "young men": "Ficção Juvenil",
    "young women": "Ficção Juvenil",
    "youth": "Ficção Juvenil",
    "zhang pian xiao shuo": "Ficção Chinesa",
    "écoles": "Gênero não definido",
}


# # Função para mapear os gêneros
# def map_genre(subject):
#     subjects_list = [s.strip().lower() for s in subject.split(",")]
#     genres = {
#         subject_to_genre.get(s, "Gênero não definido") for s in subjects_list
#     }  # Usando um set para gêneros únicos
#     return ", ".join(sorted(genres))  # Ordenar os gêneros para consistência


# # Aplicar a função para criar uma nova coluna com os gêneros mapeados
# df["Novo Gênero"] = df["Gêneros"].apply(map_genre)


# # Função para remover 'Gênero não definido' da string de gêneros
# def remove_undefined(genres):
#     genres_list = [
#         g.strip() for g in genres.split(",") if g.strip() != "Gênero não definido"
#     ]
#     return ", ".join(genres_list)


# # Remover 'Gênero não definido' das strings de gêneros
# df["Novo Gênero"] = df["Novo Gênero"].apply(remove_undefined)

# # Remover registros onde 'Novo Gênero' é vazio após a remoção
# df = df[df["Novo Gênero"].str.strip() != ""]

# # Contar o número de gêneros distintos em 'Novo Gênero' e criar a coluna 'Peso'
# df["Peso"] = df["Novo Gênero"].apply(lambda x: len(x.split(",")))

# # Salvar o DataFrame atualizado em um novo arquivo Excel
# df.to_excel("app/aux_data/base_pesos_atualizado.xlsx", index=False)

# print("DataFrame atualizado foi salvo com sucesso.")
